# ---- Étape de build ----
    FROM node:22-alpine AS builder

    # Créer et utiliser le dossier de l'application
    WORKDIR /app
    
    # Copie le fichier package.json pour installer les dépendances
    COPY package.json ./
    
    # Installe les dépendances du projet avec npm
    RUN npm install
    
    # Copier le reste des fichiers du projet
    COPY . .
    
    # Lancer le build de production
    RUN npm run build
    
    # ---- Étape finale (serveur) ----
    FROM nginx:stable-alpine-slim
    
    # Copier les fichiers générés depuis l'étape de build
    COPY --from=builder /app/dist /usr/share/nginx/html
    
    # Supprimer la config par défaut pour éviter les conflits
    RUN rm /etc/nginx/conf.d/default.conf
    
    # Copie ta config custom Nginx
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    
    # Exposer le port 80
    EXPOSE 80
    
    # Démarrer Nginx
    CMD ["nginx", "-g", "daemon off;"]